apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: techtrends
  ports:
  - name: http
    protocol: {{ .Values.service.protocol }}
    port: {{ .Values.service.port | default 3111}}
    targetPort: {{ if .Values.service.targetPort  }}{{ .Values.service.targetPort }}{{ else }}{{ .Values.service.port | default 3111 }}{{ end }} 
  type: {{ .Values.service.type }}